#%RAML 1.0 NamedExample
value:
  [

  { 
   productID: 100,
   price: 30000,
   productName: desktop,
   productType: Electronic,
   underWarranty: false
  },


   {
   productID: 101,
   price: 40000,
   productName: laptop,
   productType: Electronic,
   underWarranty: true
   }

  ]
